### ISSUE TITLE
Impove artists list

### ISSUE THREAD

**Issue by JuliaMV** [JuliaMV/culture-portal#58]
- [x] There is a bug with mobile appearance
![Screenshot_15](https://user-images.githubusercontent.com/37875890/62397219-d6c0a680-b57d-11e9-89ef-10e7ee0f61a8.png)

- [x] Also, I think we don't need a youtube video link on artist card, the read more button should be moved to the right and support other languages.
![Screenshot_19](https://user-images.githubusercontent.com/37875890/62408978-6778a000-b5d9-11e9-84ca-6886f7ed5dd4.png)

- [x] Add information about the place of birth to the artist card

- [x] Add hover effect for artists card, you can use scale or box-shadow (do not miss a transition property)

- [x] The search field should be styled and also support other languages for "not found" 

![Screenshot_13](https://user-images.githubusercontent.com/37875890/62408988-82e3ab00-b5d9-11e9-889b-810d2f94668d.png)

**Comment by anna-klempach** [comment]
Translation is already added

**Comment by JuliaMV** [comment]
Search field was styled  and translated in #71
